CREATE OR REPLACE PACKAGE PAYMENT_HISTORY
IS
    FUNCTION TOTAL_COST(PATIENT_ID NUMBER)
        RETURN NUMBER;
    FUNCTION TOTAL_PAID(PATIENT_ID NUMBER)
        RETURN NUMBER;
    PROCEDURE PAYMENT_INFO(PATIENT_ID IN PAYMENT.IDPATIENT%TYPE);
END PAYMENT_HISTORY;
CREATE OR REPLACE PACKAGE BODY PAYMENT_HISTORY
IS
    FUNCTION TOTAL_COST(
        PATIENT_ID NUMBER)
    RETURN NUMBER
    IS
        TOTAL_COST NUMBER;
    BEGIN
        SELECT SUM(AMOUNT) INTO TOTAL_COST
        FROM TREATMENTS
        WHERE IDPATIENT = PATIENT_ID;
    
        RETURN TOTAL_COST;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN RETURN 0;
    END TOTAL_COST;
    
    FUNCTION TOTAL_PAID(
        PATIENT_ID NUMBER)
    RETURN NUMBER
    IS
        PAID_AMOUNT NUMBER;
    BEGIN
        SELECT SUM(AMOUNTPAID) INTO PAID_AMOUNT
        FROM PAYMENT
        WHERE IDPATIENT = PATIENT_ID;
    
        RETURN PAID_AMOUNT;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN RETURN 0;
    END TOTAL_PAID;
    
    PROCEDURE PAYMENT_INFO(
        PATIENT_ID IN PAYMENT.IDPATIENT%TYPE)
    IS
        CUR_AMOUNTPAID NUMBER;
        CUR_PAYMENTDATE DATE;
    
        CURSOR PAYMENT_CURSOR IS
            SELECT AMOUNTPAID, PAYMENTDATE
            FROM PAYMENT
            WHERE IDPATIENT = PATIENT_ID;
    BEGIN
        OPEN PAYMENT_CURSOR;
        LOOP
        FETCH PAYMENT_CURSOR INTO CUR_AMOUNTPAID, CUR_PAYMENTDATE;
        EXIT WHEN PAYMENT_CURSOR%NOTFOUND;


        DBMS_OUTPUT.PUT_LINE('PAYMENT DATE: ' || CUR_PAYMENTDATE || ' AMOUNT PAID: ' || CUR_AMOUNTPAID);
        END LOOP;


        IF PAYMENT_CURSOR%ROWCOUNT = 0 THEN
            DBMS_OUTPUT.PUT_LINE('THIS PATIENT DOES NOT HAVE ANY PAYMENT.');
        END IF;


        CLOSE PAYMENT_CURSOR;
    END PAYMENT_INFO;
END;




-- TESTING THE PACKAGE
DECLARE
    PATIENT_ID NUMBER := 9001;
    COST_AMOUNT NUMBER;
    PAID_AMOUNT NUMBER;
    REMAIN_AMOUNT NUMBER;
BEGIN
    COST_AMOUNT := PAYMENT_HISTORY.TOTAL_COST(PATIENT_ID);
    PAID_AMOUNT := PAYMENT_HISTORY.TOTAL_PAID(PATIENT_ID);
    REMAIN_AMOUNT := COST_AMOUNT - PAID_AMOUNT;
    
    DBMS_OUTPUT.PUT_LINE('PATIENT ID: ' || PATIENT_ID);
    DBMS_OUTPUT.PUT_LINE('TOTAL COST: ' || COST_AMOUNT);
    DBMS_OUTPUT.PUT_LINE('TOTAL AMOUNT HAVE NOT PAID: ' || REMAIN_AMOUNT);
    DBMS_OUTPUT.PUT_LINE('----------------------------------------------');
    DBMS_OUTPUT.PUT_LINE('PAYMENT HISTORY:');
    
    PAYMENT_HISTORY.PAYMENT_INFO(PATIENT_ID);
END;