CREATE OR REPLACE TRIGGER APPOINTMENT_SCHEDULING
    BEFORE INSERT ON APPOINTMENTS
    FOR EACH ROW
DECLARE
    DUL_COUNT NUMBER;
    DT_FIRST DOCTORS.FIRST_NAME%TYPE;
    DT_LAST DOCTORS.LAST_NAME%TYPE;
    custom_exception EXCEPTION;
    PRAGMA EXCEPTION_INIT(custom_exception, -20001);
BEGIN
    SELECT COUNT(*)
    INTO DUL_COUNT
    FROM APPOINTMENTS
    WHERE DOCTOR_ID = :NEW.DOCTOR_ID
        AND APPOINTMENT_DATETIME = :NEW.APPOINTMENT_DATETIME;
    
    IF DUL_COUNT > 0 THEN
        SELECT FIRST_NAME, LAST_NAME
        INTO DT_FIRST, DT_LAST
        FROM DOCTORS
        WHERE ID = :NEW.DOCTOR_ID;
        
        RAISE_APPLICATION_ERROR(-20001, 
            'DOCTOR ' || DT_FIRST || ' ' || DT_LAST || ' HAS AN APPOINTMENT AT ' || 
            TO_CHAR(:NEW.APPOINTMENT_DATETIME, 'YYYY-MM-DD HH24:MI:SS') || 
            '. PLEASE CHOOSE ANOTHER SCHEDULE TIME.');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Appointment scheduled successfully.');
    END IF;
END;